networks:
  app-tier:
    driver: bridge

services:
  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    environment:
    - RABBITMQ_PLUGINS=rabbitmq_management
    ports:
    - 15672:15672
    - 5672:5672
    networks:
    - app-tier
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    environment:
    - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
    - app-tier
  kafka:
    image: 'bitnami/kafka:latest'
    environment:
    - ALLOW_PLAINTEXT_LISTENER=yes
    - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    - KAFKA_BROKER_ID=1
    - KAFKA_LISTENERS=PLAINTEXT://:9092
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    ports:
    - 9092:9092
    depends_on:
    - zookeeper
    networks:
    - app-tier
