spring:
  application:
    name: spring-cloud-function-demo
  cloud:
    stream:
      bindings:
        hire-in-0:
          binder: rabbit
        hire-out-0:
          binder: kafka
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: bitnami
  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    org:
      springframework:
        cloud:
          function: debug
